version: '1'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    env_file:
      - .env
      - ".clickhouse.${env}.env"
    ports:
      - 18123:8123 # HTTP API
      - 19000:9000 # TCP or clickhouse-client
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse
      - ./clickhouse/logs:/var/log/clickhouse-server
      - ./clickhouse/scripts:/root/scripts
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
